### ISSUE TITLE
Tutorial 32_gl_interop do the copy of FB from RAM

### ISSUE THREAD

**Issue by Flamaros** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#20]
I took a deeper look at the tutorial of the gl_interop and it isn't the optimal implementation actually.
The documentation recommend to use rprContextCreateFramebufferFromGLTexture2D to directly create the framebuffer from the GL texture to avoid the copy from VRAM to RAM and then RAM to VRAM back.

Maybe it's ok to have this slow path with the northstar backend as it is not intended to be used for real time purpose but this is critical for the hybrid backend which should be use in this tutorial IMHO.

**Comment by RichardGe** [comment]
Hi,
Because of difference of implementations between the different plugins, the interoperability with OpenGL could be different.

- with Tahoe ( the predecessor of Northstar ) interop was achieved with rprContextCreateFramebufferFromGLTexture2D.

- with Northstar, you don't have to use rprContextCreateFramebufferFromGLTexture2D. check the latest demo, I updated it with good usage ( multithread : 1 for RPR rendering, and another for OpenGL update )

- for Hybrid, I need to check with the Hybrid team, I should add a Demo for it, so we would have both Northstar and Hybrid OpenGL interop demo in our SDK tutorials.

**Comment by RichardGe** [comment]
More details for Hybrid :
rprContextCreateFramebufferFromGLTexture2D is no longer supported on Hybrid, it's Vulkan only.
I don't think we have public Demo of Hybrid+Vulkan interop. In the future we should add one in this SDK. 
In the meantime if you are interested, I can send you a quite simple standalone source code that we have internally, creating the Vulkan and Hybrid context and rendering a Cornell box.  richard . geslot <at> amd . com.

**Comment by matlemuzic** [comment]
Hi @RichardGe do you think that you could send me the source code also ? mathieu dot lemuzic at ansys dot com. Cheers
