### ISSUE TITLE
How to get access to RPR 2.0 Beta?

### ISSUE THREAD

**Issue by warvstar** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#5]
Hey guys, I can only find the repo for 1.35, how would I get access to the 2.0 beta? Also, if possible I'd like to get source access so that I can investigate porting to other platforms. Thanks

**Comment by bsavery** [comment]
We don't offer access to RPR source code without a shared license agreement.  (And I should note it's not something we offer to just everyone).  

However you can use RPR 2.0 using this repo, loading Northstar64.dll instead of Tahoe.dll from https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK/blob/66c7a759a4e343813166e2f5f700af4ee959d3b4/tutorials/00_context_creation/main.cpp#L30-L38

**Comment by bsavery** [comment]
RPR_PLUGIN_FILE_NAME expands to Tahoe.dll

**Comment by warvstar** [comment]
Good to know thanks! So what are the requirements for been offered the SLA? I'm in the process of designing a game engine and I'm looking for a raytracing library that can run on any dx12/vulkan/metal gpu. I'm also incorporated. Who do I pitch, is there an email?

**Comment by bsavery** [comment]
Sure!  Contact AMDRadeonProDeveloper@amd.com .   If you're writing your own game engine you probably want to look more at radeon Rays.  ProRender is more a higher level renderer for static scenes (like in a 3d application viewport).
