### ISSUE TITLE
There is no method to set ISO on camera

### ISSUE THREAD

**Issue by marceloroca** [GPUOpen-LibrariesAndSDKs/RadeonProRenderSDK#7]
I can read the value of sensitivity on camera (ISO) but I can't set, there is no method to do that.

https://radeon-pro.github.io/RadeonProRenderDocs/en/sdk/info_setting_types/rpr_camera_info.html?highlight=rpr_camera_response

RPR_CAMERA_RESPONSE    0x204    Sensor sensitivity (ISO).

SDK version: 1.35.3-0x92f604e2-0x00103503

**Comment by RichardGe** [comment]
The sensor sensitivity is not implemented - and I don't think it will.
The reason is that this light effect can be managed as a post-process, after render time.

---
Additional notes concerning the framebuffer data : 

the framebuffer can be exported as HDR format with `rprFrameBufferSaveToFile(fb,"file.hdr)` ,  
or you can directly access frambuffer raw data with `rprFrameBufferGetInfo(fb, RPR_FRAMEBUFFER_DATA, ...`.

- If using Tahoe plugin ( stable but in maintenance mode ),
Unresolved framebuffer are "image before post effect"
Resolved framebuffer are "image after the RPR post effect" <-- black if no post effect attached.

- If using Northstar ( successor of Tahoe, in active development )
It's advised to only access/export resolved framebuffer  ( meaning framebuffer generated by `rprContextResolveFrameBuffer` ).
There is no post-effects in Northstar. 
Unresolved framebuffer are "framebuffer in Northstar native format"
Resolved framebuffer is just "final rendering image as it's supposed to be read by API user".
The Demos of the SDK are now using Northstar as default render plugin, you can have a look how images are generated.
